# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-05 13:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fortune', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fortune',
            name='text',
            field=models.TextField(max_length=1000),
        ),
    ]
